#lang sicp
#|Exercise 1.9.  Each of the following two procedures defines a method for adding two positive integers in terms of the procedures inc, which increments its argument by 1, and dec, which decrements its argument by 1.

(define (+ a b)
  (if (= a 0)
      b
      (inc (+ (dec a) b))))

(define (+ a b)
  (if (= a 0)
      b
      (+ (dec a) (inc b))))

Using the substitution model, illustrate the process generated by each procedure in evaluating (+ 4 5). Are these processes iterative or recursive?
|#

#|
first procedure:
(+ 4 5)
(inc (+ (dec 4) 5))
(+ (+ (- 4 1) 5) 1)
(+ (+    3    5) 1)
(+ 8 1)
|#

#|
second procedure:
(+ 4 5)
(+ (dec 4) (inc 5))
(+ (- 4 1) (+ 5 1))
(+ 3 6))
|#

; both processes are iterative